services:
  db:
    image: mongo:6
    platform: linux/amd64
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db